<?php

namespace MF\CVBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
	public function getCategoryByName($name){
		$qb = $this->createQueryBuilder('c')
		  ->where('c.nom = :nom')
		  ->setParameter('nom', $name);

		$query = $qb->getQuery();

		var_dump($query->getResult());die;

		return $query->getResult();
	}
}
