<?php

namespace MF\CVBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\AST\Join;

/**
 * CompetenceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CompetenceRepository extends EntityRepository
{
	public function getOrderedCompetences()
	{
		$qb = $this->createQueryBuilder('c');
		$qb->innerJoin(
			'c.category',
			'cat',
			'WITH',
			$qb->expr()->eq('c.category', 'cat.id')
		)->orderBy('c.category');

		$query = $qb->getQuery();
		$return = array();
	
		try {	
			foreach($query->getArrayResult() as $result){
				$return[$result['nom']][] = $result;
			}
		} catch (\Exception $e) {
			var_dump($e->getMessage());die;
		}

		return $return;
	}

	public function getCompetencesByCategory($category_id)
	{
		$qb = $this->createQueryBuilder('c')
			->where('c.category = :category_id')
			->setParameter('category_id', $category_id);

		$query = $qb->getQuery();

		return $query->getResult();
	}
}
