<?php

namespace MF\CVBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * JobRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JobRepository extends EntityRepository
{
	public function getActiveJobs()
	{
		$qb = $this->createQueryBuilder('j')
		  ->where('j.is_activated = :active')
		  ->setParameter('active', true)
		  ->orderBy('j.begun_at', 'DESC');

		$query = $qb->getQuery();

		return $query->getResult();
	}
}
