MF\CVBundle\Entity\Category:
  type: entity
  repositoryClass: MF\CVBundle\Repository\CategoryRepository
  table: category
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    nom:
      type: string
      length: 255