# src/Ens/JobeetBundle/Resources/config/doctrine/Job.orm.yml
MF\CVBundle\Entity\Job:
  type: entity
  repositoryClass: MF\CVBundle\Repository\JobRepository
  table: job
  id:
    id:
      type: integer
      generator: { strategy: AUTO }
  fields:
    type:
      type: string
      length: 255
      nullable: true
    company:
      type: string
      length: 255
    logo:
      type: string
      length: 255
      nullable: true
    url:
      type: string
      length: 255
      nullable: true
    position:
      type: string
      length: 255
    location:
      type: string
      length: 255
    description:
      type: text
    token:
      type: string
      length: 255
      unique: true
    is_activated:
      type: boolean
      nullable: true
    begun_at:
      type: datetime
    ended_at:
      type: datetime
    created_at:
      type: datetime
      nullable: true
    updated_at:
      type: datetime
      nullable: true
  lifecycleCallbacks:
    prePersist: [ setCreatedAtValue ]
    preUpdate: [ setUpdatedAtValue ]
