services:
#    mf_main.example:
#        class: MF\MainBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    mf.cvmanager:
        class: MF\CVBundle\Manager\CVManager
        argumens: [@service_id, "plain_value", %mf.services.cvmanager%]
